# Generated by Django 4.2 on 2023-07-01 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_blog', '0003_comments'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='world',
            field=models.BooleanField(default=False),
        ),
    ]
