# Generated by Django 4.2 on 2023-07-01 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_blog', '0004_article_world'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='business',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='article',
            name='culture',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='article',
            name='design',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='article',
            name='health',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='article',
            name='india',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='article',
            name='opinion',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='article',
            name='politics',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='article',
            name='science',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='article',
            name='style',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='article',
            name='technology',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='article',
            name='travel',
            field=models.BooleanField(default=False),
        ),
    ]
